<!DOCTYPE html>
<html lang="{{ $locale }}" dir="{{ $isAr ? 'rtl' : 'ltr' }}">
<head>
  <meta charset="UTF-8">
  <title>{{ $isAr ? 'تقرير المدفوعات الإجمالي' : 'Bulk Payment Report' }}</title>
  <style>
    body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11px; color: #1a1a2e; direction: {{ $isAr ? 'rtl' : 'ltr' }}; }
    .page { padding: 30px; }
    .header { border-bottom: 2px solid #2563eb; padding-bottom: 15px; margin-bottom: 20px; }
    .header h1 { font-size: 18px; color: #1d4ed8; margin: 0 0 4px; }
    .header p  { color: #6b7280; margin: 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th { background: #1d4ed8; color: white; padding: 7px 10px; font-size: 10px; text-align: {{ $isAr ? 'right' : 'left' }}; }
    td { padding: 6px 10px; border-bottom: 1px solid #e5e7eb; font-size: 10px; }
    tr:nth-child(even) td { background: #f9fafb; }
    .totals { margin-top: 15px; background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 8px; padding: 10px 15px; }
    .totals p { margin: 3px 0; font-size: 11px; }
    .footer { margin-top: 20px; text-align: center; color: #9ca3af; font-size: 9px; border-top: 1px solid #e5e7eb; padding-top: 10px; }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <h1>{{ $isAr ? 'تقرير المدفوعات الإجمالي — دوبا وورك' : 'Bulk Payment Report — Dopa Work' }}</h1>
    <p>{{ $isAr ? 'الفترة:' : 'Period:' }} {{ $from }} {{ $isAr ? 'حتى' : 'to' }} {{ $to }}</p>
    <p>{{ $isAr ? 'تاريخ الإصدار:' : 'Generated:' }} {{ $generatedAt->format('d/m/Y H:i') }}</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>{{ $isAr ? 'رقم الطلب' : 'Order #' }}</th>
        <th>{{ $isAr ? 'العميل' : 'Client' }}</th>
        <th>{{ $isAr ? 'المستقل' : 'Freelancer' }}</th>
        <th>{{ $isAr ? 'المبلغ (JOD)' : 'Amount (JOD)' }}</th>
        <th>{{ $isAr ? 'العمولة (JOD)' : 'Commission (JOD)' }}</th>
        <th>{{ $isAr ? 'التاريخ' : 'Date' }}</th>
      </tr>
    </thead>
    <tbody>
      @foreach($orders as $i => $order)
      <tr>
        <td>{{ $i + 1 }}</td>
        <td>{{ $order->order_number }}</td>
        <td>{{ $order->client->name ?? '-' }}</td>
        <td>{{ $order->freelancer->name ?? '-' }}</td>
        <td>{{ number_format($order->total_amount, 3) }}</td>
        <td>{{ number_format($order->platform_fee, 3) }}</td>
        <td>{{ $order->created_at->format('d/m/Y') }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="totals">
    <p><strong>{{ $isAr ? 'إجمالي الطلبات:' : 'Total Orders:' }}</strong> {{ $orders->count() }}</p>
    <p><strong>{{ $isAr ? 'إجمالي المبالغ:' : 'Total Revenue:' }}</strong> {{ number_format($total, 3) }} JOD</p>
    <p><strong>{{ $isAr ? 'إجمالي العمولات:' : 'Total Commission:' }}</strong> {{ number_format($commission, 3) }} JOD</p>
  </div>

  <div class="footer">
    {{ $isAr ? 'وثيقة رسمية صادرة عن منصة دوبا وورك — dopawork.jo' : 'Official report generated by Dopa Work platform — dopawork.jo' }}
  </div>
</div>
</body>
</html>
